---
title: Gebruik Box Colliders om te voorkomen dat GameObjects dezelfde ruimte innemen
hero_image: images/banner.png
description: Gebruik Box Colliders om te voorkomen dat GameObjects dezelfde ruimte innemen
version: 4
listed: false
copyedit: false
last_tested: "2021-11-22"
steps:
  - title: Gebruik Box Colliders om te voorkomen dat GameObjects dezelfde ruimte innemen
