title: Utiliser des Box Colliders pour empêcher les GameObjects d'occuper le même espace
hero_image: images/banner.png
description: Utiliser des Box Colliders pour empêcher les GameObjects d'occuper le même espace
version: 4
listed: false
copyedit: false
last_tested: "2021-11-22"
steps:
  - 
    title: Utiliser des Box Colliders pour empêcher les GameObjects d'occuper le même espace
